import Head from "next/head"
import { PencilSquareIcon } from "@heroicons/react/24/solid"
import { PlusIcon } from "@heroicons/react/24/solid"
import { TrashIcon } from "@heroicons/react/24/solid"
import { CheckCircleIcon } from "@heroicons/react/24/solid"
import { CheckIcon } from "@heroicons/react/24/solid"
import React, { useState } from "react"
import Link from "next/link"

function ToDoList() {
  // Initialize state with an empty to-do list
  const [todos, setTodos] = useState([])
  const [editMode, setEditMode] = useState(false)
  const [editText, setEditText] = useState("")
  const [editIndex, setEditIndex] = useState(-1)

  // Function to add a new to-do
  const addTodo = (text) => {
    if (editMode) {
      const newTodos = [...todos]
      newTodos[editIndex] = { text }
      setTodos(newTodos)
      setEditMode(false)
      setEditText("")
      setEditIndex(-1)
    } else {
      const newTodos = [...todos, { text }]
      setTodos(newTodos)
    }
  }

  // Function to enter "edit" mode for a to-do
  const editTodo = (index) => {
    setEditMode(true)
    setEditText(todos[index].text)
    setEditIndex(index)
  }

  // Function to remove a to-do
  const deleteTodo = (index) => {
    const newTodos = [...todos]
    newTodos.splice(index, 1)
    setTodos(newTodos)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-bold flex">
        <button className="border-x border-t border-b-2 border-b-green-500 rounded-tr pt-2 flex">
          Homework
          <p> </p>
          <p className="bg-green-500 rounded-lg">1</p>
          <p>/</p>
          <p className="bg-blue-500 rounded-lg">3</p>
        </button>

        <Link href="/addLists">
          <button className="border-x border-t  rounded-tr pt-2">
            <PlusIcon className="h-6 w-6" />
          </button>
        </Link>
      </div>
      {/* Icones */}
      <div className=" flex justify-between border">
        <span className="flex">
          <div>
            <Link href="/addTasks">
              <button>
                <PlusIcon className="h-6 w-6" />
              </button>
            </Link>
          </div>

          <button>
            <PencilSquareIcon className="h-6 w-6" />
          </button>

          <button>
            <TrashIcon className="h-6 w-6" />
          </button>
        </span>
        <button>
          <CheckCircleIcon className="h-6 w-6" />
        </button>
      </div>
      <br></br>
      <div className="flex justify-center ">
        <input
          className="font-bold border-8 border-blue-500 bg-green-400 placeholder:text-blue-500"
          type="text"
          placeholder="ADD TASK"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              addTodo(e.target.value)
              e.target.value = ""
            }
          }}
        />
      </div>
      <br /> <br />
      <div className=" border-2 ">
        <ul>
          {todos.map((todo, index) => (
            <li key={index}>
              <input class="h-6 w-6 accent-green-400" type="checkbox" />
              {editMode && editIndex === index ? (
                <input
                  className="border-2 "
                  type="text"
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      addTodo(editText)
                    }
                  }}
                />
              ) : (
                todo.text
              )}

              <div className="flex justify-end">
                <button className="" onClick={() => editTodo(index)}>
                  <PencilSquareIcon className="h-6 w-6" />
                </button>
                <button className="" onClick={() => deleteTodo(index)}>
                  <TrashIcon className="h-6 w-6 " />
                </button>
              </div>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}

export default ToDoList
